project:
  type: website

website:
  title: "J.F.Koehler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: trestles
    css: styles.css
    toc: true

editor: visual



